version: 2.1

orbs:
  codecov: codecov/codecov@3

executors:
  linux:
    docker:
      - image: hanggrian/cimg-multiplatform:openjdk21.0-python3.13-node

jobs:
  upload-coverage:
    executor: linux
    steps:
      - checkout
      - run: ./gradlew check jacocoTestReport koverXmlReport
      - run: pip install -r requirements.txt && pytest --cov .
      - run: npm install && npm test
      - codecov/upload

workflows:
  build:
    jobs:
      - upload-coverage
